;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname |651|) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(define-struct movie (title producer))
... (movie-title m) ...
... (movie-producer m) ...

(define-struct boyfriend (name hair eyes phone))
... (boyfriend-name b) ...
... (boyfriend-hair b) ...
... (boyfriend-eyes b) ...
... (boyfriend-phone b) ...

(define-struct cheerleader (name number))
... (cheerleader-name c) ...
... (cheerleader-number c) ...

(define-struct CD (artist title price))
... (CD-artist d) ...
... (CD-title d) ...
... (CD-price d) ...

(define-struct sweater (material size producer))
... (sweater-material s) ...
... (sweater-size s) ...
... (sweater-producer) ...